Repository LIT-Protocol/js-sdk, pull requests merged in 2024-05, with the labels that each got.

#465 Feature/lit 3186 fix relay url set in litauthclient
  .github/workflows/ci.yml
  e2e-nodejs/group-lit-auth-client/test-should-init-with-correct-properties.mjs
  packages/lit-auth-client/src/lib/lit-auth-client.spec.ts
  packages/lit-auth-client/src/lib/lit-auth-client.ts
  packages/lit-auth-client/src/lib/relay.ts
  packages/types/src/lib/interfaces.ts
Labels: bug fix

#472 Feature/lit 3269 js sdknode fix custom auth issue
  local-tests/setup/session-sigs/get-lit-action-session-sigs.ts
  local-tests/setup/tinny-utils.ts
  local-tests/test.ts
  local-tests/tests/testUseCustomAuthSessionSigsToPkpSignExecuteJs.ts
  package.json
  packages/contracts-sdk/src/lib/auth-utils.spec.ts
  packages/contracts-sdk/src/lib/auth-utils.ts
  packages/contracts-sdk/src/lib/contracts-sdk.ts
  packages/lit-node-client-nodejs/src/lib/lit-node-client-nodejs.ts
  packages/types/src/lib/interfaces.ts
  yarn.lock
Labels: on hold for next deployment

#450 (Proposal) feat: add ResourceAbilityRequestBuilder
  packages/auth-helpers/src/index.ts
  packages/auth-helpers/src/lib/recap/resource-builder.spec.ts
  packages/auth-helpers/src/lib/recap/resource-builder.ts
Labels: Proposal
