Repository LIT-Protocol/js-sdk, pull requests merged in 2024-07, with the labels that each got.

#554 feat: add custom `nodeProtocol` and enable `https` for port `443`
  .github/workflows/ci.yml
  packages/constants/src/lib/constants/constants.ts
  packages/contracts-sdk/src/lib/contracts-sdk.ts
  packages/core/src/lib/lit-core.ts
Labels: high priority

#544 new wasm for new blsful version
  packages/bls-sdk/src/lib/bls-sdk.ts
Labels: high priority

#555 Feature/lit 3661 js sdk publish bundle general worker data before datil test
  package.json
  packages/constants/src/index.ts
  packages/constants/src/lib/constants/constants.ts
  packages/constants/src/lib/constants/mappers.ts
  packages/contracts-sdk/src/lib/contracts-sdk.ts
  tools/scripts/tools.mjs
  yarn.lock
Labels: high priority

#560 Publish version 6.2.4
  lerna.json
  packages/access-control-conditions/package.json
  packages/auth-browser/package.json
  packages/auth-helpers/package.json
  packages/bls-sdk/package.json
  packages/constants/package.json
  packages/constants/src/lib/version.ts
  packages/contracts-sdk/package.json
  packages/core/package.json
  packages/crypto/package.json
  packages/ecdsa-sdk/package.json
  packages/encryption/package.json
  packages/lit-auth-client/package.json
  packages/lit-node-client-nodejs/package.json
  packages/lit-node-client/package.json
  packages/logger/package.json
  packages/misc-browser/package.json
  packages/misc/package.json
  packages/nacl/package.json
  packages/pkp-base/package.json
  packages/pkp-client/package.json
  packages/pkp-cosmos/package.json
  packages/pkp-ethers/package.json
  packages/pkp-sui/package.json
  packages/pkp-walletconnect/package.json
  packages/sev-snp-utils-sdk/package.json
  packages/types/package.json
  packages/uint8arrays/package.json
  packages/wrapped-keys/package.json
Labels: Release

#553 LIT-3351 - Update wrapped-keys client to support multiple wrapped keys per PKP
  local-tests/setup/tinny-environment.ts
  local-tests/test.ts
  local-tests/tests/wrapped-keys/testEthereumBroadcastTransactionGeneratedKey.ts
  local-tests/tests/wrapped-keys/testEthereumBroadcastTransactionWrappedKey.ts
  local-tests/tests/wrapped-keys/testEthereumBroadcastWrappedKeyWithFetchGasParams.ts
  local-tests/tests/wrapped-keys/testEthereumSignMessageGeneratedKey.ts
  local-tests/tests/wrapped-keys/testEthereumSignMessageWrappedKey.ts
  local-tests/tests/wrapped-keys/testEthereumSignTransactionWrappedKey.ts
  local-tests/tests/wrapped-keys/testExportWrappedKey.ts
  local-tests/tests/wrapped-keys/testFailEthereumSignTransactionWrappedKeyInvalidDecryption.ts
  local-tests/tests/wrapped-keys/testFailEthereumSignTransactionWrappedKeyWithInvalidParam.ts
  local-tests/tests/wrapped-keys/testFailEthereumSignTransactionWrappedKeyWithMissingParam.ts
  local-tests/tests/wrapped-keys/testFailImportWrappedKeysWithEoaSessionSig.ts
  local-tests/tests/wrapped-keys/testFailImportWrappedKeysWithExpiredSessionSig.ts
  local-tests/tests/wrapped-keys/testFailImportWrappedKeysWithInvalidSessionSig.ts
  local-tests/tests/wrapped-keys/testFailImportWrappedKeysWithMaxExpirySessionSig.ts
  local-tests/tests/wrapped-keys/testFailImportWrappedKeysWithSamePkp.ts
  local-tests/tests/wrapped-keys/testFailImportWrappedKeysWithSamePrivateKey.ts
  local-tests/tests/wrapped-keys/testGenerateEthereumWrappedKey.ts
  local-tests/tests/wrapped-keys/testGenerateSolanaWrappedKey.ts
  local-tests/tests/wrapped-keys/testImportWrappedKey.ts
  local-tests/tests/wrapped-keys/testSignMessageWithSolanaEncryptedKey.ts
  local-tests/tests/wrapped-keys/testSignTransactionWithSolanaEncryptedKey.ts
  packages/wrapped-keys/src/index.ts
  packages/wrapped-keys/src/lib/api/export-private-key.ts
  packages/wrapped-keys/src/lib/api/generate-private-key.ts
  packages/wrapped-keys/src/lib/api/get-encrypted-key-metadata.ts
  packages/wrapped-keys/src/lib/api/get-encrypted-key.ts
  packages/wrapped-keys/src/lib/api/import-private-key.ts
  packages/wrapped-keys/src/lib/api/index.ts
  packages/wrapped-keys/src/lib/api/list-encrypted-key-metadata.ts
  packages/wrapped-keys/src/lib/api/sign-message-with-encrypted-key.ts
  packages/wrapped-keys/src/lib/api/sign-transaction-with-encrypted-key.ts
  packages/wrapped-keys/src/lib/api/store-encrypted-key.ts
  packages/wrapped-keys/src/lib/constants.ts
  packages/wrapped-keys/src/lib/lit-actions-client/export-private-key.ts
  packages/wrapped-keys/src/lib/lit-actions-client/sign-message.ts
  packages/wrapped-keys/src/lib/lit-actions-client/sign-transaction.ts
  packages/wrapped-keys/src/lib/service-client/client.ts
  packages/wrapped-keys/src/lib/service-client/index.ts
  packages/wrapped-keys/src/lib/service-client/types.ts
  packages/wrapped-keys/src/lib/service-client/utils.ts
  packages/wrapped-keys/src/lib/types.ts
Labels: high priority

#541 feat: remove PKPClient and its usages in PKPWalletConnect
  README.md
  packages/pkp-client/.babelrc
  packages/pkp-client/.eslintrc.json
  packages/pkp-client/README.md
  packages/pkp-client/jest.config.ts
  packages/pkp-client/package.json
  packages/pkp-client/project.json
  packages/pkp-client/src/index.ts
  packages/pkp-client/src/lib/pkp-client.ts
  packages/pkp-client/tsconfig.json
  packages/pkp-client/tsconfig.lib.json
  packages/pkp-client/tsconfig.spec.json
  packages/pkp-cosmos/README.md
  packages/pkp-cosmos/src/lib/pkp-cosmos.ts
  packages/pkp-walletconnect/src/lib/pkp-walletconnect.spec.ts
  packages/pkp-walletconnect/src/lib/pkp-walletconnect.ts
  typedoc.json
Labels: v7

#521 Feature/lit 3536 cleanup shiva changes
  .env.ci
  .env.sample
  .github/workflows/ci.yml
  local-tests/setup/shiva-client.ts
  local-tests/setup/tinny-environment.ts
  package.json
  yarn.lock
Labels: 🐞 Bug Fix, enhancement

#522 LIT-3688 - Handle more cases for talking to the lit nodes across epoch transitions
  local-tests/setup/tinny-environment.ts
  local-tests/setup/tinny-utils.ts
  packages/core/src/lib/lit-core.ts
Labels: enhancement, Feature

#547 Feature/lit 3582 js sdk 70 breakdown lit auth client
  local-tests/setup/tinny-person.ts
  local-tests/tests/testDelegatingCapacityCreditsNFTToAnotherPkpToExecuteJs.ts
  local-tests/tests/testRelayer.ts
  packages/lit-auth-client/README.md
  packages/lit-auth-client/src/index.ts
  packages/lit-auth-client/src/lib/lit-auth-client.spec.ts
  packages/lit-auth-client/src/lib/lit-auth-client.ts
  packages/lit-auth-client/src/lib/providers/BaseProvider.ts
  packages/lit-auth-client/src/lib/relay.ts
  packages/lit-auth-client/src/lib/utils.ts
  packages/types/src/lib/interfaces.ts
  packages/types/src/lib/types.ts
Labels: v7

#551 Feature/lit 3619 js sdk add datil mainnet support
  local-tests/build.mjs
  local-tests/setup/session-sigs/get-eoa-session-sigs.ts
  local-tests/setup/session-sigs/get-lit-action-session-sigs.ts
  local-tests/setup/session-sigs/get-pkp-session-sigs.ts
  local-tests/setup/tinny-config.ts
  local-tests/setup/tinny-environment.ts
  local-tests/setup/tinny-operations.ts
  local-tests/tests/testEthAuthSigToEncryptDecryptString.ts
  local-tests/tests/testUseCustomAuthSessionSigsToPkpSignExecuteJs.ts
  local-tests/tests/wrapped-keys/util.ts
  packages/constants/src/index.ts
  packages/constants/src/lib/constants/constants.ts
  packages/constants/src/lib/constants/mappers.ts
  packages/constants/src/lib/enums.ts
  packages/contracts-sdk/src/lib/contracts-sdk.ts
  packages/types/src/lib/types.ts
  packages/wrapped-keys/src/lib/service-client/constants.ts
  packages/wrapped-keys/src/lib/service-client/types.ts
  packages/wrapped-keys/src/lib/service-client/utils.ts
  tools/scripts/gen-internal-dev.mjs
Labels: [Dev] Don't Merge

#570 Publish version 6.4.0 [Datil Mainnet]
  .github/workflows/ci.yml
  README.md
  lerna.json
  packages/access-control-conditions/package.json
  packages/auth-browser/package.json
  packages/auth-helpers/package.json
  packages/bls-sdk/package.json
  packages/constants/package.json
  packages/constants/src/lib/version.ts
  packages/contracts-sdk/package.json
  packages/core/package.json
  packages/crypto/package.json
  packages/ecdsa-sdk/package.json
  packages/encryption/package.json
  packages/lit-auth-client/package.json
  packages/lit-node-client-nodejs/package.json
  packages/lit-node-client/package.json
  packages/logger/package.json
  packages/misc-browser/package.json
  packages/misc/package.json
  packages/nacl/package.json
  packages/pkp-base/package.json
  packages/pkp-client/package.json
  packages/pkp-cosmos/package.json
  packages/pkp-ethers/package.json
  packages/pkp-sui/package.json
  packages/pkp-walletconnect/package.json
  packages/sev-snp-utils-sdk/package.json
  packages/types/package.json
  packages/uint8arrays/package.json
  packages/wrapped-keys/package.json
Labels: Release
