Repository LIT-Protocol/js-sdk, pull requests merged in 2024-08, with the labels that each got.

#574 fix(tinny-person): for localchain it must use `custom` for network ty…
  local-tests/setup/tinny-person.ts
Labels: 🐞 Bug Fix

#563 feat: extract `formatPKPResource` and add unit tests
  packages/auth-helpers/src/lib/resources.ts
  packages/auth-helpers/src/lib/utils.spec.ts
  packages/auth-helpers/src/lib/utils.ts
Labels: 🐞 Bug Fix, enhancement

#562 add padding to LitPkpResource
  packages/auth-helpers/src/lib/resources.ts
  packages/auth-helpers/src/lib/utils.spec.ts
  packages/auth-helpers/src/lib/utils.ts
Labels: 🐞 Bug Fix

#586 Publish version 6.4.1
  lerna.json
  packages/access-control-conditions/package.json
  packages/auth-browser/package.json
  packages/auth-helpers/package.json
  packages/bls-sdk/package.json
  packages/constants/package.json
  packages/constants/src/lib/version.ts
  packages/contracts-sdk/package.json
  packages/core/package.json
  packages/crypto/package.json
  packages/ecdsa-sdk/package.json
  packages/encryption/package.json
  packages/lit-auth-client/package.json
  packages/lit-node-client-nodejs/package.json
  packages/lit-node-client/package.json
  packages/logger/package.json
  packages/misc-browser/package.json
  packages/misc/package.json
  packages/nacl/package.json
  packages/pkp-base/package.json
  packages/pkp-client/package.json
  packages/pkp-cosmos/package.json
  packages/pkp-ethers/package.json
  packages/pkp-sui/package.json
  packages/pkp-walletconnect/package.json
  packages/sev-snp-utils-sdk/package.json
  packages/types/package.json
  packages/uint8arrays/package.json
  packages/wrapped-keys/package.json
Labels: Release

#583 feat(contracts-sdk): `introduces generics T and K to improve type inf…
  packages/contracts-sdk/src/lib/contracts-sdk.ts
Labels: enhancement

#572 Ci/shiva for testing
  .env.ci
  .github/workflows/ci.yml
  local-tests/setup/shiva-client.ts
  local-tests/setup/tinny-person.ts
Labels: high priority, testing, CI

#571 AuthSig + getSessionSigs Description Updates
  packages/lit-node-client-nodejs/src/lib/lit-node-client-nodejs.ts
  packages/types/src/lib/interfaces.ts
Labels: documentation

#607 Publish version 6.4.5
  lerna.json
  packages/access-control-conditions/package.json
  packages/auth-browser/package.json
  packages/auth-helpers/package.json
  packages/bls-sdk/package.json
  packages/constants/package.json
  packages/constants/src/lib/version.ts
  packages/contracts-sdk/package.json
  packages/core/package.json
  packages/crypto/package.json
  packages/ecdsa-sdk/package.json
  packages/encryption/package.json
  packages/lit-auth-client/package.json
  packages/lit-node-client-nodejs/package.json
  packages/lit-node-client/package.json
  packages/logger/package.json
  packages/misc-browser/package.json
  packages/misc/package.json
  packages/nacl/package.json
  packages/pkp-base/package.json
  packages/pkp-client/package.json
  packages/pkp-cosmos/package.json
  packages/pkp-ethers/package.json
  packages/pkp-sui/package.json
  packages/pkp-walletconnect/package.json
  packages/sev-snp-utils-sdk/package.json
  packages/types/package.json
  packages/uint8arrays/package.json
  packages/wrapped-keys/package.json
Labels: Release

#609 feat: add `GLOBAL_OVERWRITE_IPFS_CODE_BY_NETWORK`
  local-tests/setup/session-sigs/get-lit-action-session-sigs.ts
  local-tests/tests/wrapped-keys/testFailEthereumSignTransactionWrappedKeyInvalidDecryption.ts
  packages/constants/src/lib/constants/constants.ts
  packages/constants/src/lib/constants/mappers.ts
  packages/lit-node-client-nodejs/src/lib/lit-node-client-nodejs.ts
  packages/types/src/lib/interfaces.ts
  packages/wrapped-keys/src/lib/lit-actions-client/export-private-key.ts
  packages/wrapped-keys/src/lib/lit-actions-client/generate-key.ts
  packages/wrapped-keys/src/lib/lit-actions-client/sign-message.ts
  packages/wrapped-keys/src/lib/lit-actions-client/sign-transaction.ts
Labels: high priority, urgent

#610 Publish version 6.4.6
  lerna.json
  packages/access-control-conditions/package.json
  packages/auth-browser/package.json
  packages/auth-helpers/package.json
  packages/bls-sdk/package.json
  packages/constants/package.json
  packages/constants/src/lib/version.ts
  packages/contracts-sdk/package.json
  packages/core/package.json
  packages/crypto/package.json
  packages/ecdsa-sdk/package.json
  packages/encryption/package.json
  packages/lit-auth-client/package.json
  packages/lit-node-client-nodejs/package.json
  packages/lit-node-client/package.json
  packages/logger/package.json
  packages/misc-browser/package.json
  packages/misc/package.json
  packages/nacl/package.json
  packages/pkp-base/package.json
  packages/pkp-client/package.json
  packages/pkp-cosmos/package.json
  packages/pkp-ethers/package.json
  packages/pkp-sui/package.json
  packages/pkp-walletconnect/package.json
  packages/sev-snp-utils-sdk/package.json
  packages/types/package.json
  packages/uint8arrays/package.json
  packages/wrapped-keys/package.json
Labels: Release

#602 feat: unify domain and origin default values in EthWalletProvider authenticate methods
  packages/lit-auth-client/src/lib/providers/EthWalletProvider.ts
Labels: v7

#613 Publish version 6.4.7
  lerna.json
  packages/access-control-conditions/package.json
  packages/auth-browser/package.json
  packages/auth-helpers/package.json
  packages/bls-sdk/package.json
  packages/constants/package.json
  packages/constants/src/lib/version.ts
  packages/contracts-sdk/package.json
  packages/core/package.json
  packages/crypto/package.json
  packages/ecdsa-sdk/package.json
  packages/encryption/package.json
  packages/lit-auth-client/package.json
  packages/lit-node-client-nodejs/package.json
  packages/lit-node-client/package.json
  packages/logger/package.json
  packages/misc-browser/package.json
  packages/misc/package.json
  packages/nacl/package.json
  packages/pkp-base/package.json
  packages/pkp-client/package.json
  packages/pkp-cosmos/package.json
  packages/pkp-ethers/package.json
  packages/pkp-sui/package.json
  packages/pkp-walletconnect/package.json
  packages/sev-snp-utils-sdk/package.json
  packages/types/package.json
  packages/uint8arrays/package.json
  packages/wrapped-keys/package.json
Labels: Release

#615 Publish version 6.4.8
  lerna.json
  packages/access-control-conditions/package.json
  packages/auth-browser/package.json
  packages/auth-helpers/package.json
  packages/bls-sdk/package.json
  packages/constants/package.json
  packages/constants/src/lib/version.ts
  packages/contracts-sdk/package.json
  packages/core/package.json
  packages/crypto/package.json
  packages/ecdsa-sdk/package.json
  packages/encryption/package.json
  packages/lit-auth-client/package.json
  packages/lit-node-client-nodejs/package.json
  packages/lit-node-client/package.json
  packages/logger/package.json
  packages/misc-browser/package.json
  packages/misc/package.json
  packages/nacl/package.json
  packages/pkp-base/package.json
  packages/pkp-client/package.json
  packages/pkp-cosmos/package.json
  packages/pkp-ethers/package.json
  packages/pkp-sui/package.json
  packages/pkp-walletconnect/package.json
  packages/sev-snp-utils-sdk/package.json
  packages/types/package.json
  packages/uint8arrays/package.json
  packages/wrapped-keys/package.json
Labels: Release

#580 Feature/lit 3744 js sdk from slack use getg active unkicked validator struct and counts 2
  .github/workflows/ci.yml
  local-tests/setup/networkContext.json
  local-tests/setup/tinny-environment.ts
  package.json
  packages/constants/src/lib/constants/mappers.ts
  packages/contracts-sdk/src/lib/contracts-sdk.ts
  packages/core/src/lib/lit-core.ts
  packages/types/src/lib/types.ts
  yarn.lock
Labels: high priority

#620 Publish version 6.4.10
  lerna.json
  packages/access-control-conditions/package.json
  packages/auth-browser/package.json
  packages/auth-helpers/package.json
  packages/bls-sdk/package.json
  packages/constants/package.json
  packages/constants/src/lib/version.ts
  packages/contracts-sdk/package.json
  packages/core/package.json
  packages/crypto/package.json
  packages/ecdsa-sdk/package.json
  packages/encryption/package.json
  packages/lit-auth-client/package.json
  packages/lit-node-client-nodejs/package.json
  packages/lit-node-client/package.json
  packages/logger/package.json
  packages/misc-browser/package.json
  packages/misc/package.json
  packages/nacl/package.json
  packages/pkp-base/package.json
  packages/pkp-client/package.json
  packages/pkp-cosmos/package.json
  packages/pkp-ethers/package.json
  packages/pkp-sui/package.json
  packages/pkp-walletconnect/package.json
  packages/sev-snp-utils-sdk/package.json
  packages/types/package.json
  packages/uint8arrays/package.json
  packages/wrapped-keys/package.json
Labels: Release
