Repository LIT-Protocol/js-sdk, pull requests merged in 2024-09, with the labels that each got.

#619 Fix/wasm globals
  .github/workflows/ci.yml
  packages/crypto/src/lib/crypto.ts
  packages/lit-node-client-nodejs/src/lib/lit-node-client-nodejs.ts
  packages/types/src/lib/ILitNodeClient.ts
Labels: v7

#635 Publish version 6.5.0
  README.md
  lerna.json
  packages/access-control-conditions/package.json
  packages/auth-browser/package.json
  packages/auth-helpers/package.json
  packages/bls-sdk/package.json
  packages/constants/package.json
  packages/constants/src/lib/version.ts
  packages/contracts-sdk/package.json
  packages/core/package.json
  packages/crypto/package.json
  packages/ecdsa-sdk/package.json
  packages/encryption/package.json
  packages/lit-auth-client/package.json
  packages/lit-node-client-nodejs/package.json
  packages/lit-node-client/package.json
  packages/logger/package.json
  packages/misc-browser/package.json
  packages/misc/package.json
  packages/nacl/package.json
  packages/pkp-base/package.json
  packages/pkp-client/package.json
  packages/pkp-cosmos/package.json
  packages/pkp-ethers/package.json
  packages/pkp-sui/package.json
  packages/pkp-walletconnect/package.json
  packages/sev-snp-utils-sdk/package.json
  packages/types/package.json
  packages/uint8arrays/package.json
  packages/wrapped-keys/package.json
  packages/wrapped-keys/src/lib/generated/litActions/common/exportPrivateKey.js
  packages/wrapped-keys/src/lib/generated/litActions/ethereum/generateEncryptedEthereumPrivateKey.js
  packages/wrapped-keys/src/lib/generated/litActions/ethereum/signMessageWithEthereumEncryptedKey.js
  packages/wrapped-keys/src/lib/generated/litActions/ethereum/signTransactionWithEthereumEncryptedKey.js
  packages/wrapped-keys/src/lib/generated/litActions/solana/generateEncryptedSolanaPrivateKey.js
  packages/wrapped-keys/src/lib/generated/litActions/solana/signMessageWithSolanaEncryptedKey.js
  packages/wrapped-keys/src/lib/generated/litActions/solana/signTransactionWithSolanaEncryptedKey.js
Labels: Release

#621 feat: remove jszip and compression utilities
  local-tests/test.ts
  local-tests/tests/testUseEoaSessionSigsToEncryptDecryptZip.ts
  local-tests/tests/testUsePkpSessionSigsToEncryptDecryptZip.ts
  local-tests/tests/testUseValidLitActionCodeGeneratedSessionSigsToEncryptDecryptZip.ts
  package.json
  packages/encryption/README.md
  packages/encryption/src/lib/encryption.ts
  packages/misc/src/lib/params-validators.ts
  packages/types/src/lib/interfaces.ts
  yarn.lock
Labels: v7

#622 Feature/lit 3795 review audit dependencies
  README.md
  package.json
  packages/auth-browser/src/lib/chains/eth.ts
  packages/auth-helpers/package.json
  packages/auth-helpers/src/lib/models.ts
  packages/auth-helpers/src/lib/recap/recap-session-capability-object.ts
  packages/auth-helpers/src/lib/recap/resource-builder.ts
  packages/auth-helpers/src/lib/session-capability-object.ts
  packages/constants/src/index.ts
  packages/constants/src/lib/constants/autogen_internal.ts
  packages/constants/src/lib/constants/constants.ts
  packages/constants/src/lib/constants/mappers.ts
  packages/constants/src/lib/errors.ts
  packages/contracts-sdk/package.json
  packages/contracts-sdk/src/index.ts
  packages/contracts-sdk/src/lib/addresses.ts
  packages/contracts-sdk/src/lib/contracts-sdk.ts
  packages/contracts-sdk/tsconfig.json
  packages/encryption/src/lib/encryption.ts
  packages/lit-auth-client/src/lib/providers/BaseProvider.ts
  packages/lit-auth-client/tsconfig.json
  packages/lit-node-client-nodejs/src/lib/lit-node-client-nodejs.ts
  packages/lit-node-client/tsconfig.spec.json
  packages/misc/package.json
  packages/misc/src/index.ts
  packages/misc/src/lib/addresses.spec.ts
  packages/misc/src/lib/addresses.ts
  packages/misc/tsconfig.json
  packages/pkp-base/src/lib/pkp-base.ts
  packages/pkp-cosmos/tsconfig.json
  packages/pkp-ethers/tsconfig.spec.json
  packages/types/src/lib/interfaces.ts
  packages/types/src/lib/types.ts
  packages/uint8arrays/tsconfig.json
  packages/wasm/tsconfig.base.json
  tools/scripts/gen-internal-dev.mjs
  tsconfig.base.json
  yarn.lock
Labels: v7

#637 Publish version 6.5.1
  lerna.json
  packages/access-control-conditions/package.json
  packages/auth-browser/package.json
  packages/auth-helpers/package.json
  packages/bls-sdk/package.json
  packages/constants/package.json
  packages/constants/src/lib/version.ts
  packages/contracts-sdk/package.json
  packages/core/package.json
  packages/crypto/package.json
  packages/ecdsa-sdk/package.json
  packages/encryption/package.json
  packages/lit-auth-client/package.json
  packages/lit-node-client-nodejs/package.json
  packages/lit-node-client/package.json
  packages/logger/package.json
  packages/misc-browser/package.json
  packages/misc/package.json
  packages/nacl/package.json
  packages/pkp-base/package.json
  packages/pkp-client/package.json
  packages/pkp-cosmos/package.json
  packages/pkp-ethers/package.json
  packages/pkp-sui/package.json
  packages/pkp-walletconnect/package.json
  packages/sev-snp-utils-sdk/package.json
  packages/types/package.json
  packages/uint8arrays/package.json
  packages/wrapped-keys/package.json
Labels: Release

#644 Publish version 6.5.3
  lerna.json
  packages/access-control-conditions/package.json
  packages/auth-browser/package.json
  packages/auth-helpers/package.json
  packages/bls-sdk/package.json
  packages/constants/package.json
  packages/constants/src/lib/version.ts
  packages/contracts-sdk/package.json
  packages/core/package.json
  packages/crypto/package.json
  packages/ecdsa-sdk/package.json
  packages/encryption/package.json
  packages/lit-auth-client/package.json
  packages/lit-node-client-nodejs/package.json
  packages/lit-node-client/package.json
  packages/logger/package.json
  packages/misc-browser/package.json
  packages/misc/package.json
  packages/nacl/package.json
  packages/pkp-base/package.json
  packages/pkp-client/package.json
  packages/pkp-cosmos/package.json
  packages/pkp-ethers/package.json
  packages/pkp-sui/package.json
  packages/pkp-walletconnect/package.json
  packages/sev-snp-utils-sdk/package.json
  packages/types/package.json
  packages/uint8arrays/package.json
  packages/wrapped-keys/package.json
Labels: Release

#642 feat: add session sigs validator
  packages/auth-browser/src/lib/chains/eth.ts
  packages/lit-node-client-nodejs/src/lib/lit-node-client-nodejs.ts
  packages/misc/src/index.ts
  packages/misc/src/lib/helper/session-sigs-validator.spec.ts
  packages/misc/src/lib/helper/session-sigs-validator.ts
  packages/types/src/index.ts
  packages/types/src/lib/interfaces.ts
  packages/types/src/lib/interfaces/session-sigs.ts
Labels: high priority

#645 chore: remove unused `rateLimitAuthSig` function
  packages/auth-helpers/src/lib/models.ts
  packages/auth-helpers/src/lib/recap/recap-session-capability-object.spec.ts
  packages/auth-helpers/src/lib/recap/recap-session-capability-object.ts
  packages/lit-node-client-nodejs/src/lib/lit-node-client-nodejs.ts
  packages/types/src/lib/models.ts
Labels: enhancement

#648 Publish version 6.6.0
  lerna.json
  packages/access-control-conditions/package.json
  packages/auth-browser/package.json
  packages/auth-helpers/package.json
  packages/bls-sdk/package.json
  packages/constants/package.json
  packages/constants/src/lib/version.ts
  packages/contracts-sdk/package.json
  packages/core/package.json
  packages/crypto/package.json
  packages/ecdsa-sdk/package.json
  packages/encryption/package.json
  packages/lit-auth-client/package.json
  packages/lit-node-client-nodejs/package.json
  packages/lit-node-client/package.json
  packages/logger/package.json
  packages/misc-browser/package.json
  packages/misc/package.json
  packages/nacl/package.json
  packages/pkp-base/package.json
  packages/pkp-client/package.json
  packages/pkp-cosmos/package.json
  packages/pkp-ethers/package.json
  packages/pkp-sui/package.json
  packages/pkp-walletconnect/package.json
  packages/sev-snp-utils-sdk/package.json
  packages/types/package.json
  packages/uint8arrays/package.json
  packages/wrapped-keys-lit-actions/package.json
  packages/wrapped-keys/package.json
Labels: Release

#625 ref: add non utf-8 character removal for hashing
  packages/logger/src/lib/logger.ts
Labels: medium priority

#646 feat: add skipFetchSetup to ethers providers constructor
  local-tests/setup/shiva-client.ts
  local-tests/setup/tinny-person.ts
  packages/contracts-sdk/src/lib/addresses.ts
  packages/contracts-sdk/src/lib/contracts-sdk.ts
  packages/core/src/lib/lit-core.ts
  packages/misc/src/lib/misc.ts
  packages/pkp-ethers/src/lib/pkp-ethers.ts
Labels: high priority

#657 fix: `rpcUrl` should be used when provided in the `getStakingContract` function
  packages/contracts-sdk/src/lib/contracts-sdk.ts
Labels: 🐞 Bug Fix

#658 chore: update package version to `6.7.0`
  lerna.json
  packages/access-control-conditions/package.json
  packages/auth-browser/package.json
  packages/auth-helpers/package.json
  packages/bls-sdk/package.json
  packages/constants/package.json
  packages/constants/src/lib/version.ts
  packages/contracts-sdk/package.json
  packages/core/package.json
  packages/crypto/package.json
  packages/ecdsa-sdk/package.json
  packages/encryption/package.json
  packages/lit-auth-client/package.json
  packages/lit-node-client-nodejs/package.json
  packages/lit-node-client/package.json
  packages/logger/package.json
  packages/misc-browser/package.json
  packages/misc/package.json
  packages/nacl/package.json
  packages/pkp-base/package.json
  packages/pkp-client/package.json
  packages/pkp-cosmos/package.json
  packages/pkp-ethers/package.json
  packages/pkp-sui/package.json
  packages/pkp-walletconnect/package.json
  packages/sev-snp-utils-sdk/package.json
  packages/types/package.json
  packages/uint8arrays/package.json
  packages/wrapped-keys-lit-actions/package.json
  packages/wrapped-keys/package.json
Labels: Release
