Repository LIT-Protocol/js-sdk, pull requests merged in 2024-10, with the labels that each got.

#652 fix: wrong encoding - should be `base58` instead of `base64`
  packages/wrapped-keys-lit-actions/src/lib/solana/signTransactionWithSolanaEncryptedKey.js
Labels: 🐞 Bug Fix

#665 fix: authSig should be delegated to bob's authMethodOwnedPkp instead …
  local-tests/tests/testDelegatingCapacityCreditsNFTToAnotherPkpToExecuteJs.ts
Labels: 🐞 Bug Fix

#662 feat: replace bs58 dep with ethers
  local-tests/tests/wrapped-keys/testGenerateSolanaWrappedKey.ts
  local-tests/tests/wrapped-keys/testSignMessageWithSolanaEncryptedKey.ts
  package.json
  packages/contracts-sdk/package.json
  packages/contracts-sdk/src/lib/contracts-sdk.ts
  packages/misc/src/lib/addresses.ts
  packages/pkp-sui/src/lib/TransactionBlockData.ts
  yarn.lock
Labels: ✨ Enhancement

#666 Publish version 6.8.0
  lerna.json
  packages/access-control-conditions/package.json
  packages/auth-browser/package.json
  packages/auth-helpers/package.json
  packages/bls-sdk/package.json
  packages/constants/package.json
  packages/constants/src/lib/version.ts
  packages/contracts-sdk/package.json
  packages/core/package.json
  packages/crypto/package.json
  packages/ecdsa-sdk/package.json
  packages/encryption/package.json
  packages/lit-auth-client/package.json
  packages/lit-node-client-nodejs/package.json
  packages/lit-node-client/package.json
  packages/logger/package.json
  packages/misc-browser/package.json
  packages/misc/package.json
  packages/nacl/package.json
  packages/pkp-base/package.json
  packages/pkp-client/package.json
  packages/pkp-cosmos/package.json
  packages/pkp-ethers/package.json
  packages/pkp-sui/package.json
  packages/pkp-walletconnect/package.json
  packages/sev-snp-utils-sdk/package.json
  packages/types/package.json
  packages/uint8arrays/package.json
  packages/wrapped-keys-lit-actions/package.json
  packages/wrapped-keys/package.json
Labels: Release

#664 fix/v7: Remove preinstall script to avoid local build when installing as a dependency
  packages/wasm/package.json
  packages/wasm/scripts/copyWasmBinary.mjs
Labels: 🐞 Bug Fix, v7 | Datil

#667 fix: `connection` is undefined when connecting to LitContracts
  packages/contracts-sdk/src/lib/contracts-sdk.ts
Labels: 🐞 Bug Fix

#669 Publish version 6.6.1
  lerna.json
  packages/access-control-conditions/package.json
  packages/auth-browser/package.json
  packages/auth-helpers/package.json
  packages/bls-sdk/package.json
  packages/constants/package.json
  packages/constants/src/lib/version.ts
  packages/contracts-sdk/package.json
  packages/contracts-sdk/src/lib/contracts-sdk.ts
  packages/core/package.json
  packages/crypto/package.json
  packages/ecdsa-sdk/package.json
  packages/encryption/package.json
  packages/lit-auth-client/package.json
  packages/lit-node-client-nodejs/package.json
  packages/lit-node-client/package.json
  packages/logger/package.json
  packages/misc-browser/package.json
  packages/misc/package.json
  packages/nacl/package.json
  packages/pkp-base/package.json
  packages/pkp-client/package.json
  packages/pkp-cosmos/package.json
  packages/pkp-ethers/package.json
  packages/pkp-sui/package.json
  packages/pkp-walletconnect/package.json
  packages/sev-snp-utils-sdk/package.json
  packages/types/package.json
  packages/uint8arrays/package.json
  packages/wrapped-keys-lit-actions/package.json
  packages/wrapped-keys/package.json
Labels: Patch, Release

#670 Publish version 6.7.1
  lerna.json
  packages/access-control-conditions/package.json
  packages/auth-browser/package.json
  packages/auth-helpers/package.json
  packages/bls-sdk/package.json
  packages/constants/package.json
  packages/constants/src/lib/version.ts
  packages/contracts-sdk/package.json
  packages/contracts-sdk/src/lib/contracts-sdk.ts
  packages/core/package.json
  packages/crypto/package.json
  packages/ecdsa-sdk/package.json
  packages/encryption/package.json
  packages/lit-auth-client/package.json
  packages/lit-node-client-nodejs/package.json
  packages/lit-node-client/package.json
  packages/logger/package.json
  packages/misc-browser/package.json
  packages/misc/package.json
  packages/nacl/package.json
  packages/pkp-base/package.json
  packages/pkp-client/package.json
  packages/pkp-cosmos/package.json
  packages/pkp-ethers/package.json
  packages/pkp-sui/package.json
  packages/pkp-walletconnect/package.json
  packages/sev-snp-utils-sdk/package.json
  packages/types/package.json
  packages/uint8arrays/package.json
  packages/wrapped-keys-lit-actions/package.json
  packages/wrapped-keys/package.json
Labels: Patch, Release

#668 Publish version 6.8.1
  lerna.json
  packages/access-control-conditions/package.json
  packages/auth-browser/package.json
  packages/auth-helpers/package.json
  packages/bls-sdk/package.json
  packages/constants/package.json
  packages/constants/src/lib/version.ts
  packages/contracts-sdk/package.json
  packages/core/package.json
  packages/crypto/package.json
  packages/ecdsa-sdk/package.json
  packages/encryption/package.json
  packages/lit-auth-client/package.json
  packages/lit-node-client-nodejs/package.json
  packages/lit-node-client/package.json
  packages/logger/package.json
  packages/misc-browser/package.json
  packages/misc/package.json
  packages/nacl/package.json
  packages/pkp-base/package.json
  packages/pkp-client/package.json
  packages/pkp-cosmos/package.json
  packages/pkp-ethers/package.json
  packages/pkp-sui/package.json
  packages/pkp-walletconnect/package.json
  packages/sev-snp-utils-sdk/package.json
  packages/types/package.json
  packages/uint8arrays/package.json
  packages/wrapped-keys-lit-actions/package.json
  packages/wrapped-keys/package.json
Labels: Patch, Release

#671 Remove `kintoTestnet`, Add `lineaSepolia` and `skaleCalypso`
  package.json
  packages/constants/src/lib/constants/constants.ts
  yarn.lock
Labels: Feature

#673 fix: should respect the `debug` flag when it's off
  packages/contracts-sdk/src/lib/contracts-sdk.ts
Labels: Patch

#663 Feature/lit 3918 no globalthis variables anymore
  packages/access-control-conditions/README.md
  packages/auth-browser/README.md
  packages/auth-browser/src/lib/chains/eth.ts
  packages/auth-helpers/README.md
  packages/constants/README.md
  packages/contracts-sdk/README.md
  packages/core/src/lib/lit-core.ts
  packages/crypto/README.md
  packages/encryption/README.md
  packages/lit-node-client-nodejs/src/index.ts
  packages/lit-node-client/README.md
  packages/lit-node-client/src/index.ts
  packages/misc-browser/README.md
  packages/misc/README.md
  packages/misc/src/lib/misc.ts
  packages/nacl/README.md
  packages/pkp-base/README.md
  packages/uint8arrays/README.md
  tools/scripts/gen-utils.mjs
Labels: v7 | Datil

#674 feat: add session sigs formatter/reader
  packages/lit-node-client-nodejs/src/lib/lit-node-client-nodejs.ts
  packages/misc/src/index.ts
  packages/misc/src/lib/helper/session-sigs-reader.test.ts
  packages/misc/src/lib/helper/session-sigs-reader.ts
  packages/misc/src/lib/helper/session-sigs-validator.ts
Labels: ✨ Enhancement

#676 feat: only wait for threshold nodes when signing session keys
  packages/lit-node-client-nodejs/src/lib/lit-node-client-nodejs.ts
Labels: High priority

#683 feat(bls): remove case 218 as we don't use it
  packages/crypto/src/lib/crypto.ts
Labels: ✨ Enhancement, v7 | Datil

#681 fix(test): The capacity credits NFT owner automatically uses the capacity c…
  local-tests/tests/testEthAuthSigToEncryptDecryptString.ts
Labels: 🐞 Bug Fix

#695 doc(getSessionSigs): improve jsDocs
  packages/lit-node-client-nodejs/src/lib/lit-node-client-nodejs.ts
Labels: documentation

#694 feat: add human readable format for attentuation in sessionSigs
  packages/misc/src/lib/helper/session-sigs-reader.test.ts
  packages/misc/src/lib/helper/session-sigs-reader.ts
Labels: ✨ Enhancement

#700 Publish version 6.11.0
  lerna.json
  packages/access-control-conditions/package.json
  packages/auth-browser/package.json
  packages/auth-helpers/package.json
  packages/bls-sdk/package.json
  packages/constants/package.json
  packages/constants/src/lib/version.ts
  packages/contracts-sdk/package.json
  packages/core/package.json
  packages/crypto/package.json
  packages/ecdsa-sdk/package.json
  packages/encryption/package.json
  packages/lit-auth-client/package.json
  packages/lit-node-client-nodejs/package.json
  packages/lit-node-client/package.json
  packages/logger/package.json
  packages/misc-browser/package.json
  packages/misc/package.json
  packages/nacl/package.json
  packages/pkp-base/package.json
  packages/pkp-client/package.json
  packages/pkp-cosmos/package.json
  packages/pkp-ethers/package.json
  packages/pkp-sui/package.json
  packages/pkp-walletconnect/package.json
  packages/sev-snp-utils-sdk/package.json
  packages/types/package.json
  packages/uint8arrays/package.json
  packages/wrapped-keys-lit-actions/package.json
  packages/wrapped-keys/package.json
Labels: Release

#699 feat: add types and convert lit actions to typescripts
  packages/wrapped-keys-lit-actions/esbuild.config.js
  packages/wrapped-keys-lit-actions/global.d.ts
  packages/wrapped-keys-lit-actions/src/lib/abortError.ts
  packages/wrapped-keys-lit-actions/src/lib/constants.ts
  packages/wrapped-keys-lit-actions/src/lib/internal/common/encryptKey.ts
  packages/wrapped-keys-lit-actions/src/lib/internal/common/getDecryptedKeyToSingleNode.ts
  packages/wrapped-keys-lit-actions/src/lib/internal/ethereum/generatePrivateKey.ts
  packages/wrapped-keys-lit-actions/src/lib/internal/ethereum/signMessage.js
  packages/wrapped-keys-lit-actions/src/lib/internal/ethereum/signMessage.ts
  packages/wrapped-keys-lit-actions/src/lib/internal/ethereum/signTransaction.ts
  packages/wrapped-keys-lit-actions/src/lib/internal/solana/generatePrivateKey.ts
  packages/wrapped-keys-lit-actions/src/lib/internal/solana/signMessage.js
  packages/wrapped-keys-lit-actions/src/lib/internal/solana/signMessage.ts
  packages/wrapped-keys-lit-actions/src/lib/internal/solana/signTransaction.ts
  packages/wrapped-keys-lit-actions/src/lib/litActionHandler.ts
  packages/wrapped-keys-lit-actions/src/lib/raw-action-functions/common/batchGenerateEncryptedKeys.ts
  packages/wrapped-keys-lit-actions/src/lib/raw-action-functions/common/exportPrivateKey.js
  packages/wrapped-keys-lit-actions/src/lib/raw-action-functions/common/exportPrivateKey.ts
  packages/wrapped-keys-lit-actions/src/lib/raw-action-functions/ethereum/generateEncryptedEthereumPrivateKey.ts
  packages/wrapped-keys-lit-actions/src/lib/raw-action-functions/ethereum/signMessageWithEncryptedEthereumKey.js
  packages/wrapped-keys-lit-actions/src/lib/raw-action-functions/ethereum/signMessageWithEncryptedEthereumKey.ts
  packages/wrapped-keys-lit-actions/src/lib/raw-action-functions/ethereum/signTransactionWithEncryptedEthereumKey.js
  packages/wrapped-keys-lit-actions/src/lib/raw-action-functions/ethereum/signTransactionWithEncryptedEthereumKey.ts
  packages/wrapped-keys-lit-actions/src/lib/raw-action-functions/index.js
  packages/wrapped-keys-lit-actions/src/lib/raw-action-functions/index.ts
  packages/wrapped-keys-lit-actions/src/lib/raw-action-functions/solana/generateEncryptedSolanaPrivateKey.ts
  packages/wrapped-keys-lit-actions/src/lib/raw-action-functions/solana/signMessageWithEncryptedSolanaKey.js
  packages/wrapped-keys-lit-actions/src/lib/raw-action-functions/solana/signMessageWithEncryptedSolanaKey.ts
  packages/wrapped-keys-lit-actions/src/lib/raw-action-functions/solana/signTransactionWithEncryptedSolanaKey.ts
  packages/wrapped-keys-lit-actions/src/lib/self-executing-actions/common/batchGenerateEncryptedKeys.js
  packages/wrapped-keys-lit-actions/src/lib/self-executing-actions/common/batchGenerateEncryptedKeys.ts
  packages/wrapped-keys-lit-actions/src/lib/self-executing-actions/common/exportPrivateKey.js
  packages/wrapped-keys-lit-actions/src/lib/self-executing-actions/common/exportPrivateKey.ts
  packages/wrapped-keys-lit-actions/src/lib/self-executing-actions/ethereum/generateEncryptedEthereumPrivateKey.js
  packages/wrapped-keys-lit-actions/src/lib/self-executing-actions/ethereum/generateEncryptedEthereumPrivateKey.ts
  packages/wrapped-keys-lit-actions/src/lib/self-executing-actions/ethereum/signMessageWithEncryptedEthereumKey.js
  packages/wrapped-keys-lit-actions/src/lib/self-executing-actions/ethereum/signMessageWithEncryptedEthereumKey.ts
  packages/wrapped-keys-lit-actions/src/lib/self-executing-actions/ethereum/signTransactionWithEncryptedEthereumKey.js
  packages/wrapped-keys-lit-actions/src/lib/self-executing-actions/ethereum/signTransactionWithEncryptedEthereumKey.ts
  packages/wrapped-keys-lit-actions/src/lib/self-executing-actions/solana/generateEncryptedSolanaPrivateKey.js
  packages/wrapped-keys-lit-actions/src/lib/self-executing-actions/solana/generateEncryptedSolanaPrivateKey.ts
  packages/wrapped-keys-lit-actions/src/lib/self-executing-actions/solana/signMessageWithEncryptedSolanaKey.js
  packages/wrapped-keys-lit-actions/src/lib/self-executing-actions/solana/signMessageWithEncryptedSolanaKey.ts
  packages/wrapped-keys-lit-actions/src/lib/self-executing-actions/solana/signTransactionWithEncryptedSolanaKey.js
  packages/wrapped-keys-lit-actions/src/lib/self-executing-actions/solana/signTransactionWithEncryptedSolanaKey.ts
  packages/wrapped-keys-lit-actions/tsconfig.json
  packages/wrapped-keys-lit-actions/tsconfig.lib.json
Labels: ✨ Enhancement
