Repository LIT-Protocol/js-sdk, pull requests merged in 2025-01, with the labels that each got.

#753 Publish version 7.0.4
  lerna.json
  packages/access-control-conditions/package.json
  packages/auth-browser/package.json
  packages/auth-helpers/package.json
  packages/constants/package.json
  packages/constants/src/lib/version.ts
  packages/contracts-sdk/package.json
  packages/core/package.json
  packages/crypto/package.json
  packages/encryption/package.json
  packages/event-listener/package.json
  packages/lit-auth-client/package.json
  packages/lit-node-client-nodejs/package.json
  packages/lit-node-client/package.json
  packages/logger/package.json
  packages/misc-browser/package.json
  packages/misc/package.json
  packages/nacl/package.json
  packages/pkp-base/package.json
  packages/pkp-cosmos/package.json
  packages/pkp-ethers/package.json
  packages/pkp-sui/package.json
  packages/pkp-walletconnect/package.json
  packages/types/package.json
  packages/uint8arrays/package.json
  packages/wasm/package.json
  packages/wrapped-keys-lit-actions/package.json
  packages/wrapped-keys/package.json
Labels: Release

#761 fix #760 wrapped-keys test to expect a single ACC object instead of an array
  packages/wrapped-keys/src/lib/api/utils.spec.ts
Labels: Review me

#759 fix #758 logger tests
  packages/logger/src/lib/logger.spec.ts
  packages/logger/src/lib/logger.ts
Labels: Review me

#766 fix(ci): update Rust version to 1.83.0 for wasm compatibility
  .github/workflows/ci.yml
Labels: 🐞 Bug Fix

#767 feat: add naga dev support
  package.json
  packages/constants/src/lib/constants/constants.ts
  packages/constants/src/lib/constants/mappers.ts
  packages/contracts-sdk/src/lib/contracts-sdk.ts
  packages/event-listener/package.json
  packages/lit-node-client-nodejs/src/lib/lit-node-client-nodejs.ts
  packages/types/src/lib/types.ts
  packages/wasm/rust/rust-toolchain.toml
  yarn.lock
Labels: v8 | Naga
